apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-mysql-server
  template:
    metadata:
      labels:
        app: library-mysql-server
    spec:
      containers:
      - name: library-mysql-server
        image: "mysql:8"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: library-mysql-config
              key: MYSQL_PORT
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: library-mysql-config
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: library-mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: library-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: library-mysql-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: library-mysql-storage
        persistentVolumeClaim:
          claimName: library-mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: library-mysql-service
spec:
  selector:
    app: library-mysql-server
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
