apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: java-app
        image: "mohammadrony/java-library-app:${BUILD_NUMBER}"
        ports:
        - containerPort: 8080
        imagePullPolicy: "Always"

---
apiVersion: v1
kind: Service
metadata:
  name: library-app-service
spec:
  selector:
    app: java-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
