apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-app-apache
  template:
    metadata:
      labels:
        app: library-app-apache
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: library-app-apache
        image: "mohammadrony/java-library-app:${BUILD_NUMBER}"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: library-app-service
spec:
  selector:
    app: library-app-apache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort

