CREATE USER 'libraryapp'@'%' IDENTIFIED BY '12345678abc';
GRANT ALL PRIVILEGES ON *.* TO 'libraryapp'@'%' IDENTIFIED BY '12345678abc' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS librarydb;
